### ISSUE TITLE
Server Error 500 Adding a Data Source

### ISSUE THREAD

**Issue by aascedu** [amyasnikov/validity#110]
### Validity Version

3.0.0

### NetBox Version

\>=4.0

### Python Version

3.12.3

### Steps to Reproduce

Add a data source with validity installed
Linked issue : https://github.com/netbox-community/netbox/issues/14279
Probably this file : https://github.com/amyasnikov/validity/blob/a490f08424cdfc7d74a136abcc5576db4fd21384/validity/custom_validators.py#L9
Look for the same prototype as in this file :
https://github.com/netbox-community/netbox/blob/6b219a279b3137cce351a2b48e0fb32155311aec/netbox/extras/validators.py#L168

### Traceback

![image](https://github.com/user-attachments/assets/b04b57d8-ad3b-4c28-a724-14b30a5a3e2b)

**Comment by amyasnikov** [comment]
Hey @aascedu, you're right with the root cause of the error, it's https://github.com/netbox-community/netbox/issues/14279 where an extra argument to custom validators has been added. Although it's not very polite from NetBox devs' side - to force changing the signature of all existing custom validators for all the users/developers, all I can do is to fix it.

As an immediate fix you can temporarily remove the custom validator from your configuration.py

**Comment by aascedu** [comment]
Thank you so much, I downgraded my Netbox version to 3.7 which is style
functional. I will wait for your fix as it shouldn’t take long to update.
Thank you so much for being as reactive as that ! You will make work easier
when it’s fixed ;)

Have a good one.
Arthur
